import Head from "next/head"
import styles from "../styles/Home.module.scss"
import Header from "../components/Header"
import Navbar from "../components/Navbar"
import Hero from "../components/Hero"
import HeroSvg from "../components/HeroSvg"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>👋 Hello There!</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1,
 minimum-scale=1"
                ></meta>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={styles.main}>
                <HeroSvg />
                <Hero />
                <Navbar />
            </main>

            {/* <footer className={styles.footer}></footer> */}
        </div>
    )
}
