import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.scss"
import Header from "../components/Header"
import Cta from '../components/Cta'
import Hero from '../components/Hero'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>👋 Hello There!</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <main className={styles.main}>
                <Hero/>
                <Cta/>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    )
}
